[log]
filepath = "./log/crontab.log"
max_size = 50       # 单个文件最大大小（MB）
max_backups = 10    # 最多保留旧文件数
max_age = 7         # 最多保留天数
compress = true     # 是否压缩

[msgconfig]
addr = ""
app_key = ""
secret_key = ""
phone = ""
userid = ""

[[program]]
name = ""
status_cmd = ""
start_cmd = ""

[[program]]
name = ""
status_cmd = ""
start_cmd = ""
