[[program]]
name = "myapp"
path = "/home/user/myapp"

[[program]]
name = "anotherapp"
path = "/opt/anotherapp"

[log]
filepath = "/var/log/crontab.log"
max_size = 10
max_backups = 5
max_age = 30
compress = true

[msgconfig]
addr = "http://sms.example.com"
app_key = "encrypted_appkey"
secret_key = "encrypted_secretkey"
phone = "1234567890"
userid = "1001"
